permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM
sass:
  style: compressed
gems:
  - jekyll-sitemap

# 作者信息
author: 
  name: 胡明星
  email: yopoing@vip.qq.com
  link: http://humingxing.com
  weibo: http://t.qq.com/yopoing
  github: http://github.com/yopoing

# 站点信息
title: 胡明星的个人博客 
keyword: python,django,flask,tornado,java,php,mysql,原创教程
description: 胡明星，网名鸟嘌呤、yopoing,专注于IT培训、网络教育和web编程技术的研究，分享原创中文精品教程。
url: http://humingxing.com
rss_url: /rss.xml

# avatar头像及Favicon
avatar: http://7xlr6o.com1.z0.glb.clouddn.com/avatar.png
favicon: http://7xlr6o.com1.z0.glb.clouddn.com/favicon.ico

# google analytics 设置
ga:
  id: UA-67472688-1
  url: humingxing.com

# disqus 设置
disqus:
  shortname: yopoing
